title: Cenus Open Innovation Labs
description: >- # this means to ignore newlines until "baseurl:"
  Trailblazing open government through cross-sector collaboration, design, and technology.
# url: "https://coil.census.gov" # the base hostname & protocol for your site, e.g. http://example.com

email: census.openinnovationlabs@census.gov
top-form: https://www.census.gov/forms/contact-top.html

google_analytics_gtm: G-E5HT6RV40X

# Build settings
# theme: uswds-jekyll
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - cypress/
  - cypress.json
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - jekyll/
  - LICENSE.md
  - pa11y.json
  - package.json
  - package-lock.json
  - node_modules/
  - README.md
  - scripts/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - img
  - files
